const products = [
    // --- Categoría: Bebés / Estimulación (0-3 años) ---
    {
        id: 1,
        name: "Baby Alive Muñeca Grows Up Lala GooGoo",
        price: 710.00,
        oldPrice: null,
        category: "bebes",
        badge: "Interactivo",
        badgeClass: "highlight",
        icon: "fas fa-baby",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=Baby+Alive+Grows+Up"
    },
    {
        id: 5,
        name: "Dear Mia Little Liz | Cubo de Actividades",
        price: 350.00,
        oldPrice: null,
        category: "bebes",
        badge: "Montessori",
        badgeClass: "success",
        icon: "fas fa-shapes",
        rating: 4.6,
        image: "https://placehold.co/300x300?text=Cubo+Actividades"
    },
    {
        id: 6,
        name: "Muñeca Bebe Nenuco, Adivina Lo Que Veo",
        price: 610.00,
        oldPrice: null,
        category: "bebes",
        badge: null,
        badgeClass: "",
        icon: "fas fa-baby",
        rating: 4.3,
        image: "https://placehold.co/300x300?text=Nenuco+Adivina"
    },
    {
        id: 15,
        name: "Bus Escolar Cocomelon 2 En 1",
        price: 750.00,
        oldPrice: null,
        category: "bebes",
        badge: "Musical",
        badgeClass: "info",
        icon: "fas fa-bus",
        rating: 4.7,
        image: "https://placehold.co/300x300?text=Bus+Cocomelon"
    },

    // --- Categoría: Preescolar (3-5 años) ---
    {
        id: 2,
        name: "FurReal Walkalots Grandes Paseos - Mascota interactiva",
        price: 655.00,
        oldPrice: null,
        category: "3-5",
        badge: "Top Regalo",
        badgeClass: "highlight",
        icon: "fas fa-dog",
        rating: 4.8,
        image: "https://placehold.co/300x300?text=FurReal+Walkalots"
    },
    {
        id: 8,
        name: "Play-Doh Set Moto Repartidora de Pizzas",
        price: 1000.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-motorcycle",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=PlayDoh+Pizza"
    },
    {
        id: 14,
        name: "Alberca Infantil Inflable Bluey",
        price: 530.00,
        oldPrice: null,
        category: "3-5",
        badge: "Verano",
        badgeClass: "info",
        icon: "fas fa-swimming-pool",
        rating: 4.7,
        image: "https://placehold.co/300x300?text=Alberca+Bluey"
    },
    {
        id: 16,
        name: "Paw Patrol: Chase Guardián Peluche Interactivo",
        price: 955.00,
        oldPrice: null,
        category: "3-5",
        badge: "Luz y Sonido",
        badgeClass: "highlight",
        icon: "fas fa-paw",
        rating: 4.9,
        image: "https://placehold.co/300x300?text=Chase+Paw+Patrol"
    },
    {
        id: 17,
        name: "Paw Patrol Camión de Bomberos Marshall",
        price: 1350.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-truck-monster",
        rating: 4.8,
        image: "https://placehold.co/300x300?text=Marshall+FireTruck"
    },
    {
        id: 19,
        name: "PIN Y PON Pinypon",
        price: 710.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-users",
        rating: 4.4,
        image: "https://placehold.co/300x300?text=Pinypon"
    },
    {
        id: 20,
        name: "Plastilina Play-Doh 2 piezas",
        price: 50.00,
        oldPrice: null,
        category: "3-5",
        badge: "Económico",
        badgeClass: "success",
        icon: "fas fa-palette",
        rating: 4.0,
        image: "https://placehold.co/300x300?text=PlayDoh+Pack"
    },
    {
        id: 31,
        name: "Play-Doh Iron Man Armor Maker Lab",
        price: 360.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-robot",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=PlayDoh+IronMan"
    },
    {
        id: 32,
        name: "Play-Doh Marvel Spider-Man Lanza y Atrapa",
        price: 360.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-spider",
        rating: 4.4,
        image: "https://placehold.co/300x300?text=PlayDoh+Spiderman"
    },
    {
        id: 34,
        name: "Play-Doh Kitchen Creations Pasteles Divertidos",
        price: 240.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-birthday-cake",
        rating: 4.6,
        image: "https://placehold.co/300x300?text=PlayDoh+Pasteles"
    },

    // --- Categoría: Escolar / Acción (6-9 años) ---
    {
        id: 7,
        name: "NERF - Lanzador Elite Jr Flyer Easy-Play",
        price: 155.00,
        oldPrice: null,
        category: "6-9",
        badge: "Básico",
        badgeClass: "",
        icon: "fas fa-crosshairs",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=NERF+Elite+Jr"
    },
    {
        id: 9,
        name: "Nerf N Series Lanzador Infinite (80 Dardos)",
        price: 610.00,
        oldPrice: null,
        category: "6-9",
        badge: "Potente",
        badgeClass: "highlight",
        icon: "fas fa-bullseye",
        rating: 4.7,
        image: "https://placehold.co/300x300?text=Nerf+Infinite"
    },
    {
        id: 10,
        name: "Nerf Junior Wild Lionfury",
        price: 205.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-paw",
        rating: 4.4,
        image: "https://placehold.co/300x300?text=Nerf+Lionfury"
    },
    {
        id: 11,
        name: "Nerf Dino Squad",
        price: 210.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-dragon",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=Nerf+Dino+Squad"
    },
    {
        id: 12,
        name: "NERF N Series Pinpoint (18 Dardos)",
        price: 290.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-crosshairs",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=Nerf+Pinpoint"
    },
    {
        id: 18,
        name: "Sonic 3 Set De Batalla Cangrejo Mecha",
        price: 650.00,
        oldPrice: null,
        category: "6-9",
        badge: "Gamer",
        badgeClass: "info",
        icon: "fas fa-gamepad",
        rating: 4.8,
        image: "https://placehold.co/300x300?text=Sonic+Battle+Set"
    },
    {
        id: 22,
        name: "Peluche Adopt Me! Sorpresa",
        price: 220.00,
        oldPrice: null,
        category: "6-9",
        badge: "Sorpresa",
        badgeClass: "info",
        icon: "fas fa-gift",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=Adopt+Me+Peluche"
    },

    // --- Categoría: Juegos de Mesa (Familia / +6 años) ---
    {
        id: 23,
        name: "Juego De Mesa Atrapa Ratones Clásico",
        price: 510.00,
        oldPrice: null,
        category: "juegos",
        badge: "Clásico",
        badgeClass: "",
        icon: "fas fa-mouse",
        rating: 4.6,
        image: "https://placehold.co/300x300?text=Atrapa+Ratones"
    },
    {
        id: 24,
        name: "Hasbro Gaming Operando Clásico",
        price: 425.00,
        oldPrice: null,
        category: "juegos",
        badge: null,
        badgeClass: "",
        icon: "fas fa-user-md",
        rating: 4.7,
        image: "https://placehold.co/300x300?text=Operando"
    },
    {
        id: 25,
        name: "Hypershot Juego De Mesa 5 En 1 (Usado)",
        price: 280.00,
        oldPrice: null,
        category: "juegos",
        badge: "Usado",
        badgeClass: "warning",
        icon: "fas fa-dice",
        rating: 4.0,
        image: "https://placehold.co/300x300?text=Hypershot"
    },
    {
        id: 26,
        name: "Turista Mundial Universal Studios",
        price: 160.00,
        oldPrice: null,
        category: "juegos",
        badge: "Oferta",
        badgeClass: "success",
        icon: "fas fa-plane",
        rating: 4.3,
        image: "https://placehold.co/300x300?text=Turista+Mundial"
    },
    {
        id: 27,
        name: "Juego De Mesa Destreza",
        price: 345.00,
        oldPrice: null,
        category: "juegos",
        badge: "Agilidad",
        badgeClass: "",
        icon: "fas fa-hourglass-half",
        rating: 4.5,
        image: "https://placehold.co/300x300?text=Destreza"
    },
    {
        id: 28,
        name: "Monopoly Knockout",
        price: 420.00,
        oldPrice: null,
        category: "juegos",
        badge: "Nuevo",
        badgeClass: "highlight",
        icon: "fas fa-money-bill-wave",
        rating: 4.6,
        image: "https://placehold.co/300x300?text=Monopoly+Knockout"
    },
    {
        id: 29,
        name: "Jumanji: El Juego (Edición Clásica)",
        price: 280.00,
        oldPrice: null,
        category: "juegos",
        badge: "Aventura",
        badgeClass: "",
        icon: "fas fa-drum",
        rating: 4.4,
        image: "https://placehold.co/300x300?text=Jumanji"
    },
    {
        id: 30,
        name: "Puerquito Enojon Juego Electronico",
        price: 360.00,
        oldPrice: null,
        category: "juegos",
        badge: null,
        badgeClass: "",
        icon: "fas fa-piggy-bank",
        rating: 4.1,
        image: "https://placehold.co/300x300?text=Puerquito+Enojon"
    },

    // --- Categoría: Coleccionables / Avanzados (10-12+ años) ---
    {
        id: 3,
        name: "4D Build Hulkbuster Marvel (348 Piezas, Luz LED)",
        price: 740.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Premium",
        badgeClass: "dark",
        icon: "fas fa-robot",
        rating: 5.0,
        image: "https://placehold.co/300x300?text=Hulkbuster+4D"
    },
    {
        id: 4,
        name: "4D Build Escudo Capitán América",
        price: 610.00,
        oldPrice: null,
        category: "coleccionables",
        badge: null,
        badgeClass: "",
        icon: "fas fa-shield-alt",
        rating: 4.9,
        image: "https://placehold.co/300x300?text=Escudo+Capitan"
    },
    {
        id: 13,
        name: "Marvel Legends: Máscara Spider-Man Homecoming",
        price: 2600.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Ed. Limitada",
        badgeClass: "dark",
        icon: "fas fa-mask",
        rating: 5.0,
        image: "https://placehold.co/300x300?text=Spiderman+Mask"
    },
    {
        id: 21,
        name: "Marvel Legends: Casco Duende Verde Premium",
        price: 2800.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Exclusivo",
        badgeClass: "dark",
        icon: "fas fa-user-secret",
        rating: 5.0,
        image: "https://placehold.co/300x300?text=Duende+Verde+Helm"
    },

    // --- Categoría: Varios / General ---
    {
        id: 33,
        name: "Set De Masas Play Doh Microscopio Luminoso",
        price: 280.00,
        oldPrice: null,
        category: "educativos",
        badge: "Ciencia",
        badgeClass: "info",
        icon: "fas fa-microscope",
        rating: 4.3,
        image: "https://placehold.co/300x300?text=Microscopio+PlayDoh"
    },
    {
        id: 35,
        name: "King Homer - Los Simpsons (Jakks Pacific)",
        price: 850.00,
        oldPrice: null,
        category: "varios",
        badge: "Colección",
        badgeClass: "",
        icon: "fas fa-tv",
        rating: 4.7,
        image: "https://placehold.co/300x300?text=King+Homer"
    },
    {
        id: 36,
        name: "El Perro Slinky (Toy Story)",
        price: 940.00,
        oldPrice: null,
        category: "varios",
        badge: "Retro",
        badgeClass: "",
        icon: "fas fa-dog",
        rating: 4.8,
        image: "https://placehold.co/300x300?text=Slinky+Dog"
    },
    {
        id: 37,
        name: "The Ugglys Pug Electronic Pet",
        price: 550.00,
        oldPrice: null,
        category: "varios",
        badge: "Divertido",
        badgeClass: "warning",
        icon: "fas fa-grin-tongue",
        rating: 4.2,
        image: "https://placehold.co/300x300?text=Ugglys+Pug"
    }
];