const products = [
    // =========================================
    // CATEGORÍA: BEBÉS Y ESTIMULACIÓN (0-3 AÑOS)
    // =========================================
    {
        id: 1,
        name: "Baby Alive Muñeca Grows Up Lala GooGoo",
        price: 710.00,
        oldPrice: null,
        category: "bebes",
        badge: "Interactivo",
        badgeClass: "highlight",
        icon: "fas fa-baby",
        rating: 4.8,
        description: "Crece de recién nacida a niña. Incluye accesorios interactivos.",
        image: "assets/images/1.jpg"
    },
    {
        id: 2,
        name: "Dear Mia Little Liz | Cubo de Actividades Montessori",
        price: 350.00,
        oldPrice: null,
        category: "bebes",
        badge: "Educativo",
        badgeClass: "success",
        icon: "fas fa-shapes",
        rating: 4.6,
        description: "Cubo didáctico para motricidad fina y estimulación temprana.",
        image: "assets/images/2.jpg"
    },
    {
        id: 3,
        name: "Muñeca Bebe Nenuco, Adivina Lo Que Veo",
        price: 610.00,
        oldPrice: null,
        category: "bebes",
        badge: null,
        badgeClass: "",
        icon: "fas fa-baby-carriage",
        rating: 4.3,
        description: "Muñeca clásica interactiva para cuidados básicos.",
        image: "assets/images/3.jpg"
    },
    {
        id: 4,
        name: "Bus Escolar Cocomelon 2 En 1",
        price: 750.00,
        oldPrice: null,
        category: "bebes",
        badge: "Musical",
        badgeClass: "info",
        icon: "fas fa-bus",
        rating: 4.7,
        description: "Autobús musical con luces y sonidos de la serie.",
        image: "assets/images/4.jpg"
    },

    // =========================================
    // CATEGORÍA: PREESCOLAR (3-5 AÑOS)
    // =========================================
    {
        id: 5,
        name: "FurReal Walkalots Grandes Paseos - Mascota Interactiva",
        price: 655.00,
        oldPrice: null,
        category: "3-5",
        badge: "Más Vendido",
        badgeClass: "highlight",
        icon: "fas fa-dog",
        rating: 4.8,
        description: "Mascota electrónica que camina y hace sonidos reales.",
        image: "assets/images/5.jpg"
    },
    {
        id: 6,
        name: "Paw Patrol: Chase Guardián Peluche Interactivo",
        price: 955.00,
        oldPrice: null,
        category: "3-5",
        badge: "Luz y Sonido",
        badgeClass: "highlight",
        icon: "fas fa-shield-alt",
        rating: 4.9,
        description: "Peluche con linterna y frases de la patrulla canina.",
        image: "assets/images/6.jpg"
    },
    {
        id: 7,
        name: "Paw Patrol Camión de Bomberos Marshall",
        price: 1350.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-truck-monster",
        rating: 4.9,
        description: "Camión de rescate transformable con figura de Marshall.",
        image: "assets/images/7.jpg"
    },
    {
        id: 8,
        name: "Play-Doh Set Moto Repartidora de Pizzas",
        price: 1000.00,
        oldPrice: null,
        category: "3-5",
        badge: "Creativo",
        badgeClass: "success",
        icon: "fas fa-motorcycle",
        rating: 4.5,
        description: "Set de modelado para crear y entregar pizzas de juguete.",
        image: "assets/images/8.jpg"
    },
    {
        id: 9,
        name: "Alberca Infantil Inflable Bluey",
        price: 530.00,
        oldPrice: null,
        category: "3-5",
        badge: "Verano",
        badgeClass: "info",
        icon: "fas fa-water",
        rating: 4.7,
        description: "Alberca resistente con diseño de Bluey y Bingo.",
        image: "assets/images/9.jpg"
    },
    {
        id: 10,
        name: "Play-Doh Iron Man Armor Maker Lab",
        price: 360.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-robot",
        rating: 4.5,
        description: "Laboratorio para crear armaduras de Iron Man con masa.",
        image: "assets/images/10.jpg"
    },
    {
        id: 11,
        name: "Play-Doh Marvel Spider-Man Lanza y Atrapa",
        price: 360.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-spider",
        rating: 4.4,
        description: "Figura de Spider-Man con acción de telaraña Play-Doh.",
        image: "assets/images/11.jpg"
    },
    {
        id: 12,
        name: "Play-Doh Kitchen Creations Pasteles Divertidos",
        price: 240.00,
        oldPrice: null,
        category: "3-5",
        badge: "Oferta",
        badgeClass: "warning",
        icon: "fas fa-birthday-cake",
        rating: 4.6,
        description: "Set básico de repostería creativa.",
        image: "assets/images/12.jpg"
    },
    {
        id: 13,
        name: "PIN Y PON Pinypon",
        price: 710.00,
        oldPrice: null,
        category: "3-5",
        badge: null,
        badgeClass: "",
        icon: "fas fa-users",
        rating: 4.4,
        description: "Set de figuras intercambiables Pinypon.",
        image: "assets/images/13.jpg"
    },
    {
        id: 14,
        name: "Plastilina Play-Doh 2 piezas",
        price: 50.00,
        oldPrice: null,
        category: "3-5",
        badge: "Básico",
        badgeClass: "",
        icon: "fas fa-palette",
        rating: 4.0,
        description: "Botes de repuesto de masa Play-Doh.",
        image: "assets/images/14.jpg"
    },
    {
        id: 15,
        name: "The Ugglys Pug Electronic Pet",
        price: 550.00,
        oldPrice: null,
        category: "3-5",
        badge: "Divertido",
        badgeClass: "",
        icon: "fas fa-dog",
        rating: 4.2,
        description: "Mascota electrónica interactiva con sonidos graciosos.",
        image: "assets/images/15.jpg"
    },

    // =========================================
    // CATEGORÍA: ESCOLAR Y ACCIÓN (6-9 AÑOS)
    // =========================================
    {
        id: 16,
        name: "Nerf N Series Lanzador Infinite (80 Dardos)",
        price: 610.00,
        oldPrice: null,
        category: "6-9",
        badge: "Novedad",
        badgeClass: "highlight",
        icon: "fas fa-crosshairs",
        rating: 4.7,
        description: "Lanzador de alta capacidad con sistema de recarga fácil.",
        image: "assets/images/16.jpg"
    },
    {
        id: 17,
        name: "Nerf Dino Squad",
        price: 210.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-dragon",
        rating: 4.5,
        description: "Lanzador con diseño de dinosaurio T-Rex.",
        image: "assets/images/17.jpg"
    },
    {
        id: 18,
        name: "NERF Lanzador Elite Jr Flyer",
        price: 155.00,
        oldPrice: null,
        category: "6-9",
        badge: "Económico",
        badgeClass: "success",
        icon: "fas fa-bullseye",
        rating: 4.5,
        description: "Diseñado para manos pequeñas, fácil de cargar.",
        image: "assets/images/18.jpg"
    },
    {
        id: 19,
        name: "Nerf Junior Wild Lionfury",
        price: 205.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-paw",
        rating: 4.4,
        description: "Lanzador con diseño de león.",
        image: "assets/images/19.jpg"
    },
    {
        id: 20,
        name: "NERF N Series Pinpoint (18 Dardos)",
        price: 290.00,
        oldPrice: null,
        category: "6-9",
        badge: null,
        badgeClass: "",
        icon: "fas fa-crosshairs",
        rating: 4.5,
        description: "Lanzador de precisión para puntería.",
        image: "assets/images/20.jpg"
    },
    {
        id: 21,
        name: "Sonic 3 Set De Batalla Cangrejo Mecha",
        price: 650.00,
        oldPrice: null,
        category: "6-9",
        badge: "Gamer",
        badgeClass: "info",
        icon: "fas fa-gamepad",
        rating: 4.8,
        description: "Set de batalla con figura de Sonic y robot villano.",
        image: "assets/images/21.jpg"
    },
    {
        id: 22,
        name: "Peluche Adopt Me! Sorpresa",
        price: 220.00,
        oldPrice: null,
        category: "6-9",
        badge: "Sorpresa",
        badgeClass: "",
        icon: "fas fa-box-open",
        rating: 4.5,
        description: "Peluche sorpresa del popular juego de Roblox.",
        image: "assets/images/22.jpg"
    },

    // =========================================
    // CATEGORÍA: JUEGOS DE MESA (FAMILIAR)
    // =========================================
    {
        id: 23,
        name: "Monopoly Knockout",
        price: 420.00,
        oldPrice: null,
        category: "juegos",
        badge: "Nuevo",
        badgeClass: "highlight",
        icon: "fas fa-money-bill-wave",
        rating: 4.6,
        description: "Versión rápida y activa del clásico Monopoly.",
        image: "assets/images/23.jpg"
    },
    {
        id: 24,
        name: "Juego De Mesa Atrapa Ratones Clásico",
        price: 510.00,
        oldPrice: null,
        category: "juegos",
        badge: "Clásico",
        badgeClass: "",
        icon: "fas fa-mouse",
        rating: 4.6,
        description: "Juego de construcción de trampas y acción en cadena.",
        image: "assets/images/24.jpg"
    },
    {
        id: 25,
        name: "Hasbro Gaming Operando Clásico",
        price: 425.00,
        oldPrice: null,
        category: "juegos",
        badge: null,
        badgeClass: "",
        icon: "fas fa-user-md",
        rating: 4.7,
        description: "Pon a prueba tu pulso y saca las piezas sin tocar los bordes.",
        image: "assets/images/25.jpg"
    },
    {
        id: 26,
        name: "Turista Mundial Universal Studios",
        price: 160.00,
        oldPrice: null,
        category: "juegos",
        badge: "Oferta",
        badgeClass: "success",
        icon: "fas fa-globe-americas",
        rating: 4.3,
        description: "El clásico juego de viajes edición Universal.",
        image: "assets/images/26.jpg"
    },
    {
        id: 27,
        name: "Juego De Mesa Destreza",
        price: 345.00,
        oldPrice: null,
        category: "juegos",
        badge: "Agilidad",
        badgeClass: "",
        icon: "fas fa-hourglass-half",
        rating: 4.5,
        description: "Coloca las piezas antes de que salten por el aire.",
        image: "assets/images/27.jpg"
    },
    {
        id: 28,
        name: "Jumanji: El Juego (Edición Clásica)",
        price: 280.00,
        oldPrice: null,
        category: "juegos",
        badge: "Aventura",
        badgeClass: "",
        icon: "fas fa-drum",
        rating: 4.4,
        description: "El juego que te persigue. Cuidado con la selva.",
        image: "assets/images/28.jpg"
    },
    {
        id: 29,
        name: "Hypershot Juego De Mesa 5 En 1",
        price: 280.00,
        oldPrice: null,
        category: "juegos",
        badge: "Usado/Outlet",
        badgeClass: "warning",
        icon: "fas fa-dice",
        rating: 4.0,
        description: "Consola de juegos electrónicos de mesa.",
        image: "assets/images/29.jpg"
    },
    {
        id: 30,
        name: "Puerquito Enojon Juego Electronico",
        price: 360.00,
        oldPrice: null,
        category: "juegos",
        badge: null,
        badgeClass: "",
        icon: "fas fa-piggy-bank",
        rating: 4.1,
        description: "Juego de acción y suerte para niños.",
        image: "assets/images/30.jpg"
    },

    // =========================================
    // CATEGORÍA: COLECCIONABLES (10+ AÑOS / ADULTOS)
    // =========================================
    {
        id: 31,
        name: "Marvel Legends: Casco Duende Verde Premium",
        price: 2800.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Exclusivo",
        badgeClass: "dark",
        icon: "fas fa-mask",
        rating: 5.0,
        description: "Réplica 1:1 detallada del casco de Norman Osborn.",
        image: "assets/images/31.jpg"
    },
    {
        id: 32,
        name: "Marvel Legends: Máscara Spider-Man Homecoming",
        price: 2600.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Ed. Limitada",
        badgeClass: "dark",
        icon: "fas fa-spider",
        rating: 5.0,
        description: "Máscara electrónica con ojos expresivos ajustables.",
        image: "assets/images/32.jpg"
    },
    {
        id: 33,
        name: "4D Build Hulkbuster Marvel (348 Piezas)",
        price: 740.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Premium",
        badgeClass: "dark",
        icon: "fas fa-robot",
        rating: 5.0,
        description: "Puzzle 3D detallado de la armadura Hulkbuster con soporte.",
        image: "assets/images/33.jpg"
    },
    {
        id: 34,
        name: "4D Build Escudo Capitán América",
        price: 610.00,
        oldPrice: null,
        category: "coleccionables",
        badge: null,
        badgeClass: "",
        icon: "fas fa-shield-alt",
        rating: 4.9,
        description: "Modelo para armar en 3D del escudo icónico.",
        image: "assets/images/34.jpg"
    },
    {
        id: 35,
        name: "King Homer - Los Simpsons (Jakks Pacific)",
        price: 850.00,
        oldPrice: null,
        category: "coleccionables",
        badge: "Colección",
        badgeClass: "",
        icon: "fas fa-tv",
        rating: 4.8,
        description: "Figura de colección de Homero King Kong.",
        image: "assets/images/35.jpg"
    },

    // =========================================
    // CATEGORÍA: VARIOS / EDUCACIÓN
    // =========================================
    {
        id: 36,
        name: "Set De Masas Play Doh Microscopio Luminoso",
        price: 280.00,
        oldPrice: null,
        category: "educativos",
        badge: "Ciencia",
        badgeClass: "info",
        icon: "fas fa-microscope",
        rating: 4.3,
        description: "Juguete STEAM para explorar texturas como un científico.",
        image: "assets/images/36.jpg"
    },
    {
        id: 37,
        name: "El Perro Slinky (Toy Story)",
        price: 940.00,
        oldPrice: null,
        category: "varios",
        badge: "Retro",
        badgeClass: "",
        icon: "fas fa-dog",
        rating: 4.8,
        description: "El clásico perro de resorte de las películas de Pixar.",
        image: "assets/images/37.jpg"
    }
];